//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO2Neutral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaRecomendacion
    {
        public CategoriaRecomendacion()
        {
            this.Recomendacion = new HashSet<Recomendacion>();
        }
    
        public int idCategoria { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Recomendacion> Recomendacion { get; set; }
    }
}
