//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO2Neutral.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_TestEntities : DbContext
    {
        public BD_TestEntities()
            : base("name=BD_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calculadora> Calculadora { get; set; }
        public DbSet<CategoriaRecomendacion> CategoriaRecomendacion { get; set; }
        public DbSet<CentroAcopio> CentroAcopio { get; set; }
        public DbSet<listaFrecuencias> listaFrecuencias { get; set; }
        public DbSet<listaMedios> listaMedios { get; set; }
        public DbSet<MedioTransporte> MedioTransporte { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Recomendacion> Recomendacion { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<EstadisticaTransporte> EstadisticaTransporte { get; set; }
    }
}
