//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO2Neutral_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculadora
    {
        public Calculadora()
        {
            this.MedioTransporte = new HashSet<MedioTransporte>();
        }
    
        public int idUsuario { get; set; }
        public int idCalculdora { get; set; }
        public Nullable<int> resultadoTransporte { get; set; }
        public Nullable<int> resultadoElectricidad { get; set; }
        public Nullable<int> resultadoReciclaje { get; set; }
        public Nullable<int> resultadoGas { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<MedioTransporte> MedioTransporte { get; set; }
    }
}
